---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "biscot"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::biscot=2.3.3"
